### PR TITLE
Return the actual returned data, not a copy

### PR DESCRIPTION
**Pull request by josemarluedke**
This is possible a breaking change.

I was trying to figure out why do we always return a copy of the data instead of the actual data. 

Does anyone have context on why we ever did this? Also, is this still required? Tests still pass when removing it.

cc/ @bgentry

### CODE REVIEW

**Comment by christophermlne** [comment]
Probably to avoid two-way data bindings.

**Comment by bgentry** [comment]
The reason this was done originally was so that watch queries would work correctly; I needed an Ember.Object (or something eventable) that I could easily replace the payload of when a new version became available from Apollo Client, and afaik I couldn’t do that with a POJO at the time. That meant that any computed properties or views which were chained on that object would get updated correctly the moment the underlying object was updated. However I think this may have only worked correctly at the top level properties because we weren’t nesting Ember.Objects or Arrays.

I would be extra careful to ensure that this still works without the wrapping Object as watch queries are one of the big perks of Apollo Client, and making them play nice with Ember was one of the original goals of this project. :v:

**Comment by bgentry** [comment]
Additionally I will point out that every time a new watch query payload is sent by Apollo, you’re already getting a unique/new copy of that POJO. So the challenge is providing a wrapper in Ember land that the watch query subscription manager can update when new versions come in.

**Comment by josemarluedke** [comment]
Thanks for the explanation, that really helps me understand previous decisions. I have pushed a commit that adds a test to make sure we don't regress on watchQuery + computed.

All tests are passing, so I think I'm fine moving this forward. Although, I don't think this is a breaking change I will leave marked as such for folks to be on the lookout for bugs related to this.

**Pull request merged**
