### PR TITLE
Upgrade to ember-auto-import@2

### PR DESCRIPTION
**Pull request by balinterdi**

### CODE REVIEW

**Comment by josemarluedke** [comment]
@balinterdi Can you rebase this PR?

**Comment by balinterdi** [comment]
@josemarluedke Sure, I would but when #413 failed for me, I started looking into what causes the tests to fail and it seemed like being on `ember-auto-import@1` was one of the potential issues so I wanted to see whether upgrading the add-on to `ember-auto-import@2` fixes it.

**Comment by josemarluedke** [comment]
I will merge this and get tests passing in other PR. Thanks @balinterdi.

**Comment by balinterdi** [comment]
@josemarluedke Thank you very much!

**Comment by josemarluedke** [comment]
Published as v4.0.0.

**Pull request merged**
