### PR TITLE
Using nested fragments creates invalid graphql document

### PR DESCRIPTION
**Pull request by lstrzebinczyk**
Hello

I found a case that will create an invalid graphql request. I created a failing test case to reproduce the issue in this PR, but to give this a description:

1. Have a query with fragment, in my case that is `TeamFragment`
2. Have a different fragment in the same query, in my case that is `GameFragment`
3. `GameFragment` also has `TeamFragment`
4. Generated graphql request now has the `TeamFragment` definition twice, and the graphql at the backend rejects the request

What I would expect to happen: The graphql document will deduplicate the fragment definitions, as nested fragments are a valid case.

If anyone can point me to a right direction, I can throw some more time at solving this, but at this point the code is a little bit cryptic to me, I'm having troubles figuring out where the graphql document building takes place.

Thank you.

### CODE REVIEW

**Comment by jasonmit** [comment]
Feels related to an upstream issue: https://github.com/csantero/broccoli-graphql-filter/issues/1

I haven't verified if the latest changes in 0.4.1 resolve it or not.

**Comment by omairvaiyani** [comment]
I can confirm that 0.4.1 resolved this issue for me.

**Comment by lstrzebinczyk** [comment]
I merged current master to this branch, but the test is still failing. Any idea why that might be?

**Comment by josemarluedke** [comment]
@lstrzebinczyk Thanks for merging with master. I was surprised this wasn't fixed with the latest version of `broccoli-graphql-filter`. Do you mind opening a PR in `broccoli-graphql-filter` with these tests? Essentially, this needs to be fixed there before we are able to make our tests pass.

cc/ @csantero

**Comment by lstrzebinczyk** [comment]
Here it is: https://github.com/csantero/broccoli-graphql-filter/pull/10

However, as stated in that PR, unless I'm not understanding the js representaton correctly, it seams that `broccoli-graphql-filter` is handling the thing right?

**Comment by josemarluedke** [comment]
@lstrzebinczyk Thanks for getting that PR up. That did prove it should pass here, so I dug into what could it be happening here, first I thought it could be a miss-match of graphql version from broccoli-graphql-filter and us, but that wasn't the case. I ended up reviewing a bit more and figure out it was just a few typos. I just pushed a commit here and it should be good now.

Thanks for pusing this to the finish line. Will merge as soon as tests pass. csantero/broccoli-graphql-filter#10 should also be merged IMO.

**Comment by lstrzebinczyk** [comment]
Well. That's embarassing : O. I'm happy we brought this to an end : )

**Comment by topbloc-beiswenger** [comment]
Running into this issue now on 2.0.0

**Pull request merged**
